# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0006_auto_20190803_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eshopapp.Cart'),
        ),
    ]
