# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0008_middlwarenotifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiddlwareNotifications',
            new_name='MiddlwareNotification',
        ),
    ]
